name: markdown_docs
description: Markdown code generation for flutter.
version: 1.0.0-dev.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0