name: markdown_docs
description: Markdown code generation for flutter.
version: 1.0.0-dev.4
homepage: https://adrianos42.github.io/markdown_docs_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0